### ISSUE TITLE
after updating to 8.20.2 - error: command 'latex-workshop.build' not found

### ISSUE THREAD

**Issue by magix2** [James-Yu/LaTeX-Workshop#2847]
### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Problem description

After updating to 8.20.2 and trying to build, i get the following error: command 'latex-workshop.build' not found

When installing another version, e.g. 8.19.2 it works without any problems.

### To Reproduce

1. open *.tex
2. Ctrl + Alt + b
3. error: command 'latex-workshop.build' not found

### Expected behavior

Building a pdf

## Logs

There are no logs, the output is empty

### Developer Tools Console [Required]

```
Activating extension 'James-Yu.latex-workshop' failed: Cannot find module '/home/chris/.vscode-oss/extensions/james-yu.latex-workshop-8.20.2/out/src/main.js'
Require stack:
- /usr/lib/code/out/vs/loader.js
- /usr/lib/code/out/bootstrap-amd.js
- /usr/lib/code/out/bootstrap-fork.js.
$onExtensionActivationError @ workbench.desktop.main.js:2350

```
The directory src does not exist. There are only other directories in in .vscode-oss/extensions/james-yu.latex-workshop-8.20.2/out/
data
resources
snippets
viewer

## Desktop [Required]

Please write exact version numbers. Please don't write `latest` instead of exact numbers.

 - OS: Linux Arch
 - VS Code version: [e.g. 1.58.0]
 - Extension version: 8.20.2 not working, 8.19.2 working
 - TeX distribution version: TeX 3.141592653 (TeX Live 2021/Arch Linux)

### Are you using VSCodium?

No, not VSCodium, I am using the open source version of code.

### Are you using the Snap or Flatpack versions of VS Code?

No

### Are you using LaTeX Workshop with VS Code Remote?

No
